apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ali-lasemi/platform-cicd-toolkit.git
    targetRevision: main
    path: templates/gitops/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
