resources:
  - ../../base

namespace: development

replicas:
  - name: platform-app
    count: 1

images:
  - name: ghcr.io/example/platform-app
    newName: ghcr.io/example/platform-app
    newTag: initial
